name: Run Tests and Check Coverage

on:
  pull_request:
    branches: [main]  # or your main dev branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # or your version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest with coverage
      run: |
        pytest --cov=app_server tests/ --cov-fail-under=80
